# Generated by Django 4.2.5 on 2023-10-21 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.curso'),
            preserve_default=False,
        ),
    ]
