# Generated by Django 4.2.5 on 2023-10-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_estudiante_id_usuario_estudiante_id_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default='prueba ', max_length=50),
            preserve_default=False,
        ),
    ]
