# Generated by Django 4.2.5 on 2023-10-18 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCurso',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255)),
                ('descripcion_categoria', models.TextField()),
            ],
            options={
                'verbose_name': 'Categoría Curso',
                'verbose_name_plural': 'Categorías Curso',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=255)),
                ('descripcion_curso', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('duracion', models.IntegerField()),
                ('horarios', models.CharField(max_length=255)),
                ('establecimiento', models.CharField(max_length=255)),
                ('costo', models.FloatField()),
                ('cupos_disponibles', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.categoriacurso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
